### ISSUE TITLE
Specify a working folder

### ISSUE THREAD

**Issue by Ked57** [replayio/action-upload#30]
Hello, first of all thank you for this github action. I've been trying to make it work in a monorepo and when I run the action with 

```
      # Always run this step so failed tests are uploaded
      - name: Upload replays
        if: always()
        uses: replayio/action-upload@v0.5.1
        with:
          api-key: ${{ secrets.RECORD_REPLAY_API_KEY }}
```
I get an error 
<img width="1166" alt="image" src="https://github.com/replayio/action-upload/assets/2174111/62589dbb-8940-4b95-9221-a95f4c7dccee">

I realize the app folder is at `apps/client` so that might be the problem but I can't find a solution because github actions don't allow the `working_directory` directive for `use` actions. Cypress has a `project: ./apps/client` argument which makes it work for my purpose.

Is there any plan for this kind of feature, I might be able to help implement it

Thank you
